name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Backend
    - name: Backend - Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Backend - Run tests
      working-directory: ./backend
      run: npm test
      
    - name: Backend - Check security
      working-directory: ./backend
      run: npm audit --audit-level=moderate

    - name: Backend - Build (if applicable)
      working-directory: ./backend
      run: npm run build || echo "No build step required for backend"

    # Frontend
    - name: Frontend - Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Frontend - Run tests
      working-directory: ./frontend
      run: npm test
      
    - name: Frontend - Check security
      working-directory: ./frontend
      run: npm audit --audit-level=moderate

    - name: Frontend - Build
      working-directory: ./frontend
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
    - name: Simulate deployment
      run: echo "Deploying the solution"